require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'addsAppodeal' do
  config = use_native_modules!
  use_native_modules!
  use_frameworks!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  def appodeal
    pod 'APDAdjustAdapter', '3.0.2.1'
    pod 'APDAppLovinAdapter', '3.0.2.1'
    pod 'APDAppsFlyerAdapter', '3.0.2.1'
    pod 'APDBidMachineAdapter', '3.0.2.1' # Required
    pod 'BidMachineAmazonAdapter', '~> 2.0.0.0'
    pod 'BidMachineCriteoAdapter', '~> 2.0.0.0'
    pod 'BidMachineSmaatoAdapter', '~> 2.0.0.0'
    pod 'BidMachineTapjoyAdapter', '~> 2.0.0.0'
    pod 'BidMachinePangleAdapter', '~> 2.0.0.0'
    pod 'BidMachineNotsyAdapter', '~> 2.0.0.4'
    pod 'APDFirebaseAdapter', '3.0.2.1'
    pod 'APDGoogleAdMobAdapter', '3.0.2.1'
    pod 'APDIABAdapter', '3.0.2.1' # Required
    pod 'APDFacebookAdapter', '3.0.2.1'
    pod 'APDMyTargetAdapter', '3.0.2.1'
    pod 'BidMachineMyTargetAdapter', '~> 2.0.0.2'
    pod 'APDStackAnalyticsAdapter', '3.0.2.1' # Required
    pod 'Appodeal/Banner', '~> 2.10.0.1'
    pod 'Appodeal/Interstitial', '~> 2.10.0.1'
    pod 'Appodeal/Native', '~> 2.10.0.1'
  end

  target 'addsAppodealTests' do
    pod 'Appodeal/Banner'
    pod 'Appodeal/Interstitial'
    pod 'Appodeal/Native'
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
